---
- name: ensure the install log file is created
  win_tempfile:
    path: "{{ app_install_dir }}"
    prefix: TableauServerInstaller_
    suffix: .log
    state: file
  register: log_file

- name: ensure the version file is created
  win_file:
    path: "{{ tableau_version_file_path }}"
    state: touch

- name: tableau primary install
  win_package:
    path: "{{ tableau_install_exe_path }}"
    product_id: TableauServer{{ tableau_target_version }}_is1
    creates_path: "{{ tableau_install_dir }}"
    arguments: >
      /VERYSILENT
      /SUPPRESSMSGBOXES
      /ACCEPTEULA
      /LOG="{{ log_file.path }}"
      /DIR="{{ tableau_install_dir }}"
      /DATADIR="{{ tableau_install_dir }}"
      /CONTROLLERPORT={{ tableau_controller_port }}
      /VERSIONFILE="{{ tableau_version_file_path }}"
    state: present
  async: 600 # escape winrm job memory limits by using async

- name: tableau controller ui
  debug:
    msg: https://{{ ansible_host }}:{{ tableau_controller_port }}
