---
- name: fail if tableau_target_version is not defined
  fail:
    msg: missing required variable `tableau_target_version`
  when: tableau_target_version is not defined
  run_once: yes

- name: fail if tableau_bin_dir is not defined
  fail:
    msg: missing required variable `tableau_bin_dir`
  when: tableau_bin_dir is not defined
  run_once: yes

- name: fail if tableau_install_dir is not defined
  fail:
    msg: missing required variable `tableau_install_dir`
  when: tableau_install_dir is not defined
  run_once: yes

- name: fail if tableau_node_bootstrap_config_path is not defined
  fail:
    msg: missing required variable `tableau_node_bootstrap_config_path`
  when: tableau_node_bootstrap_config_path is not defined
  run_once: yes
